/**
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer.validation;

import de.protos.ontolizer.validation.AbstractOntolizerValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OntolizerValidator extends AbstractOntolizerValidator {
}
