/*
 * generated by Xtext 2.9.1
 */
package de.protos.ontolizer.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOntolizerScopeProvider extends DelegatingScopeProvider {
}
