/**
 * generated by Xtext 2.9.1
 */
package de.protos.ontolizer.ontolizer;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edge List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.protos.ontolizer.ontolizer.EdgeList#getEdgeType <em>Edge Type</em>}</li>
 *   <li>{@link de.protos.ontolizer.ontolizer.EdgeList#getEdges <em>Edges</em>}</li>
 * </ul>
 *
 * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getEdgeList()
 * @model
 * @generated
 */
public interface EdgeList extends EObject
{
  /**
   * Returns the value of the '<em><b>Edge Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Edge Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edge Type</em>' reference.
   * @see #setEdgeType(EdgeType)
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getEdgeList_EdgeType()
   * @model
   * @generated
   */
  EdgeType getEdgeType();

  /**
   * Sets the value of the '{@link de.protos.ontolizer.ontolizer.EdgeList#getEdgeType <em>Edge Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Edge Type</em>' reference.
   * @see #getEdgeType()
   * @generated
   */
  void setEdgeType(EdgeType value);

  /**
   * Returns the value of the '<em><b>Edges</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.ontolizer.ontolizer.Edge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Edges</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edges</em>' containment reference list.
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getEdgeList_Edges()
   * @model containment="true"
   * @generated
   */
  EList<Edge> getEdges();

} // EdgeList
