/**
 * generated by Xtext 2.9.1
 */
package de.protos.ontolizer.ontolizer;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.protos.ontolizer.ontolizer.Edge#getTargetNode <em>Target Node</em>}</li>
 * </ul>
 *
 * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getEdge()
 * @model
 * @generated
 */
public interface Edge extends EObject
{
  /**
   * Returns the value of the '<em><b>Target Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Node</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Node</em>' reference.
   * @see #setTargetNode(Node)
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getEdge_TargetNode()
   * @model
   * @generated
   */
  Node getTargetNode();

  /**
   * Sets the value of the '{@link de.protos.ontolizer.ontolizer.Edge#getTargetNode <em>Target Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Node</em>' reference.
   * @see #getTargetNode()
   * @generated
   */
  void setTargetNode(Node value);

} // Edge
