/**
 * generated by Xtext 2.9.1
 */
package de.protos.ontolizer.ontolizer;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.protos.ontolizer.ontolizer.Model#getNodeTypes <em>Node Types</em>}</li>
 *   <li>{@link de.protos.ontolizer.ontolizer.Model#getEdgeTypes <em>Edge Types</em>}</li>
 *   <li>{@link de.protos.ontolizer.ontolizer.Model#getNodes <em>Nodes</em>}</li>
 *   <li>{@link de.protos.ontolizer.ontolizer.Model#getViews <em>Views</em>}</li>
 * </ul>
 *
 * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Node Types</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.ontolizer.ontolizer.NodeType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Types</em>' containment reference list.
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getModel_NodeTypes()
   * @model containment="true"
   * @generated
   */
  EList<NodeType> getNodeTypes();

  /**
   * Returns the value of the '<em><b>Edge Types</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.ontolizer.ontolizer.EdgeType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Edge Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edge Types</em>' containment reference list.
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getModel_EdgeTypes()
   * @model containment="true"
   * @generated
   */
  EList<EdgeType> getEdgeTypes();

  /**
   * Returns the value of the '<em><b>Nodes</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.ontolizer.ontolizer.Node}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nodes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' containment reference list.
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getModel_Nodes()
   * @model containment="true"
   * @generated
   */
  EList<Node> getNodes();

  /**
   * Returns the value of the '<em><b>Views</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.ontolizer.ontolizer.View}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Views</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Views</em>' containment reference list.
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getModel_Views()
   * @model containment="true"
   * @generated
   */
  EList<View> getViews();

} // Model
