/**
 * generated by Xtext 2.9.1
 */
package de.protos.ontolizer.ontolizer;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.protos.ontolizer.ontolizer.Node#getNodeType <em>Node Type</em>}</li>
 *   <li>{@link de.protos.ontolizer.ontolizer.Node#getName <em>Name</em>}</li>
 *   <li>{@link de.protos.ontolizer.ontolizer.Node#getSummary <em>Summary</em>}</li>
 *   <li>{@link de.protos.ontolizer.ontolizer.Node#getEdgeLists <em>Edge Lists</em>}</li>
 * </ul>
 *
 * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Node Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Type</em>' reference.
   * @see #setNodeType(NodeType)
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getNode_NodeType()
   * @model
   * @generated
   */
  NodeType getNodeType();

  /**
   * Sets the value of the '{@link de.protos.ontolizer.ontolizer.Node#getNodeType <em>Node Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Type</em>' reference.
   * @see #getNodeType()
   * @generated
   */
  void setNodeType(NodeType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getNode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.protos.ontolizer.ontolizer.Node#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Summary</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Summary</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Summary</em>' attribute list.
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getNode_Summary()
   * @model unique="false"
   * @generated
   */
  EList<String> getSummary();

  /**
   * Returns the value of the '<em><b>Edge Lists</b></em>' containment reference list.
   * The list contents are of type {@link de.protos.ontolizer.ontolizer.EdgeList}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Edge Lists</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edge Lists</em>' containment reference list.
   * @see de.protos.ontolizer.ontolizer.OntolizerPackage#getNode_EdgeLists()
   * @model containment="true"
   * @generated
   */
  EList<EdgeList> getEdgeLists();

} // Node
