/**
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer.generator;

import com.google.inject.Inject;
import de.protos.ontolizer.generator.DotGenerator;
import de.protos.ontolizer.generator.HTMLGenerator;
import de.protos.ontolizer.generator.JSONGenerator;
import de.protos.ontolizer.generator.ModelSerializer;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class OntolizerGenerator extends AbstractGenerator {
  @Inject
  private DotGenerator dotGenerator;
  
  @Inject
  private ModelSerializer modelSerializer;
  
  @Inject
  private JSONGenerator jsonGenerator;
  
  @Inject
  private HTMLGenerator htmlGenerator;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    this.dotGenerator.doGenerate(resource, fsa, context);
    this.modelSerializer.doGenerate(resource, fsa, context);
    this.jsonGenerator.doGenerate(resource, fsa, context);
    this.htmlGenerator.doGenerate(resource, fsa, context);
  }
}
