/*
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer.validation

import de.protos.ontolizer.ontolizer.DepthRange
import de.protos.ontolizer.ontolizer.OntolizerPackage.Literals
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class OntolizerValidator extends AbstractOntolizerValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					OntolizerPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkDepthRange(DepthRange it){
		if(start == 0)
			warning("default '0' represents infinite depth, statement is expendable", it, Literals.DEPTH_RANGE__START)
		else if(end != 0 && start > end)
			error('depth must be an numeric interval', it, null)
	}
}
