/*
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OntolizerAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/protos/ontolizer/parser/antlr/internal/InternalOntolizer.tokens");
	}
}
