/**
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer.ui;

import de.protos.ontolizer.ui.AbstractOntolizerUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OntolizerUiModule extends AbstractOntolizerUiModule {
  public OntolizerUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
