/*
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OntolizerStandaloneSetup extends OntolizerStandaloneSetupGenerated {

	def static void doSetup() {
		new OntolizerStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
