/**
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer;

import de.protos.ontolizer.OntolizerStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntolizerStandaloneSetup extends OntolizerStandaloneSetupGenerated {
  public static void doSetup() {
    OntolizerStandaloneSetup _ontolizerStandaloneSetup = new OntolizerStandaloneSetup();
    _ontolizerStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
