/**
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer;

import de.protos.ontolizer.AbstractOntolizerRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntolizerRuntimeModule extends AbstractOntolizerRuntimeModule {
}
