/**
 * generated by Xtext 2.9.2
 */
package de.protos.ontolizer.ui.contentassist;

import de.protos.ontolizer.ui.contentassist.AbstractOntolizerProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OntolizerProposalProvider extends AbstractOntolizerProposalProvider {
}
